@startuml
'https://plantuml.com/use-case-diagram


left to right direction
actor Employees as employees
actor Manager as manager
:Insurance Company: as insurance_company
:User: as user

rectangle Car_rental_System{

usecase Login as login
usecase Registration as registration
(Search Car) as search
(Select Car) as select
(Reservation) as reservation
(Maintain Car Information) as maintain
(View Daily Rental Reports) as view_daily_rental_reports
(View Monthly Rental Reports) as view_monthly_rental_reports
(Generate Bill) as generate_bill
(Bill Payment) as bill
}

'maintain the order of use cases
user -up-> login
user -up-> registration
user -up-> search
user -up-> select
user -up-> bill
insurance_company -up-> bill
employees --> login
employees --> maintain
manager --> view_monthly_rental_reports
employees --> view_daily_rental_reports
employees --> generate_bill

@enduml