@startuml
'https://plantuml.com/use-case-diagram

'complete

left to right direction
"Client" as client
"Account Manager" as account_manager
"Invoicing Officer" as invoicing_officer

rectangle Reservation {
(Consult offer) as consult
(Reserve Trip) as reserve
(Cancel Trip) as cancel
(Consult order status) as consult_order_status
(Invoice) as invoice
(Cancel Invoice) as cancel_invoice
}

skinparam actorStyle awesome
"Trip" as trip
"Order" as orders
"Invoicing" as invoicing
"ReserveTrip" as ReserveTrip

client --> consult
client --> reserve
client --> cancel
account_manager --> reserve
account_manager --> cancel
account_manager --> consult_order_status
invoicing_officer --> invoice
invoicing_officer --> cancel_invoice
trip -up-> consult : <<realizes>>
ReserveTrip -up-> reserve : <<realizes>>
ReserveTrip -up-> cancel : <<cancel>>
orders -up-> consult_order_status : <<realizes>>
invoicing -up-> invoice : <<realizes>>
invoicing -up-> cancel_invoice : <<realizes>>


@enduml