@startuml
'https://plantuml.com/object-diagram

left to right direction
object "Camping Trip" as camping
camping : Code
camping : StartDate
camping : EndDate

object Scout
Scout : Name
Scout : Date Of Birth
Scout : Date Joined

object "Wealthy Scout" as wealthy
wealthy : Last Donation Amount

object "Camp site" as camp_site
camp_site : Name
camp_site : Location

object "Badge Awarded" as badge_awarded
badge_awarded : Date

object "Badge Specific" as badge_specification
badge_specification : Code
badge_specification : Name
badge_specification : Description

camping "*" -- "*" Scout
camping "*" -- "1" camp_site
Scout "1" -- "*" badge_awarded
badge_awarded "*" -- "1" badge_specification
wealthy --|> Scout


@enduml
