@startuml

actor "Developer" <<Person>> as ADEV
actor "Expert" <<Person>> as AEXPR
actor "Subscriber" <<Person>> as ASUBSCR
actor "Workforce" <<Person>> as AWF
actor "Anonymous" <<Person>> as AU

component "Tokyo" <<Software System>> as CQS

usecase (develops and deploys new versions) as UC1
usecase UC2 as "
logins,
manages profile,
reviews and updates quizzes content"
usecase UC3 as "
logins,
manages profile,
receives notifications,
reviews available quizzes,
assigns quiz,
review results,
reports feedback"
usecase UC4 as "
logins,
manages profile,
receives quiz assignments,
passes quizzes"
usecase UC5 as (signs up)

ADEV -down-> UC1
UC1 -down-> CQS
AEXPR -down-> UC2
UC2 -down-> CQS
ASUBSCR -up-> UC3
UC3 -up-> CQS
AWF -up-> UC4
UC4 -up-> CQS
AU -down-> UC5
UC5 -down-> CQS


@enduml