@startuml
'https://plantuml.com/use-case-diagram

':Main Admin: as Admin
'(Use the application) as (Use)
'
'User -> (Start)
'User --> (Use)
'
'Admin ---> (Use)
'
'note right of Admin : This is an example.
'
'note right of (Use)
'A note can also
'be on several lines
'end note
'
'note "This note is connected\nto several objects." as N2
'(Start) .. N2
'N2 .. (Use)
left to right direction
skinparam actorStyle awesome
actor Waitor as waiter
actor Client as client
:Cashier: as cashier
:Chef: as chef

 rectangle System_Boundary{
(Order\nFood) as orderfood
(Cook\nFood) as cookfood
(Serve\nFood) as servefood
(Eat\nFood)  as eatfood
(Pay for Food) as payfood

(Order\nWine) as orderwine
(Serve\nWine) as servewine
(Drink\nWine) as drinkwine
(Pay for Wine) as paywine
}

waiter --> orderfood : receive food
waiter --> servefood
waiter --> payfood : faciliate payment
client --> orderfood : place order
client --> eatfood
client --> payfood : pay
cashier -> payfood : accept payment
chef --> orderfood : confirm order
chef --> cookfood

orderwine --> orderfood : <<extend>>
servewine --> servefood : <<extend>> {if wine was ordered}
drinkwine --> eatfood : <<extend>> {if wine was served}
paywine --> payfood : <<extend>> {if wine was consumed}

@enduml